version: '3.1'

services:
  web:
    image: pbadhe34/my-apps:user-app
    ports:
       - "8090"
    networks:
       - webnet     
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_pass
      MYSQL_DATABASE: userservice
      MYSQL_USER: app-user
      MYSQL_PASSWORD: /run/secrets/db_pass
    volumes:
       - "/mysql/data:/var/lib/mysql"
    secrets:
      - db_pass
    networks:
       - webnet
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet 
networks:
  webnet:

secrets:
      db_pass:
      external: true
